/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_jni_ControlHelper */

#ifndef _Included_com_jni_ControlHelper
#define _Included_com_jni_ControlHelper
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_jni_ControlHelper
 * Method:    openLED
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_jni_ControlHelper_openLED
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
